[package]
name = "hlddup"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
log = "0.4.22"
seahash = { version = "4.1.0", features = ["use_std"] }
walkdir = "2.5.0"

[profile.release]
debug = true
